### ISSUE TITLE
Shields not included in sets...

### ISSUE THREAD

**Issue by Scappotto** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#235]
Hi, 
i'm having a problem with the app, i've a lot of shields in my recipe tabs, but the program is not including them in sets, it just consider the weapons only, i've tried 3 and 6 space weapons, but no 4 space shields.

![image](https://user-images.githubusercontent.com/36949456/129330758-0d114310-c208-4538-a9bc-0801e5964a79.png)

i had the 1.2.4 version, unistalled and installed the new 1.2.6, but i've the same behaviour, it's an issue or i can't use shields for sets?
thanks for the help

**Comment by Aradiv** [comment]
Shields can be used for the recipe but the tool doesn't consider them.

**Comment by HiMarioLopez** [comment]
Copying and pasting from my pull-request comments:

So, we don't have shields on the recipe to save space. This was a design decision.

The smallest shields will take up 4 units of space in the inventory/stash (2x2), with the smallest weapon being 3 units (3x1), we'll have a set min equaling 7 total units.

With a two-hander you take up 6 units, or with 2 min-sized one-handed weapons you will take up the same 6 units.

I think to stay consistent with that I'll look at taking out the one-handed thrusting weapons from the app, since those can take up to 4x1 spaces.
