### ISSUE TITLE
Loot filter syncing not working

### ISSUE THREAD

**Issue by Moregaze** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#237]
Anytime I hit the R icon in 1.2.6 it just pastes whatever I last cntrl copied into chat.  No idea why or how to send you a log or anything to help sort that out.

**Comment by Moregaze** [comment]
![image](https://user-images.githubusercontent.com/14935217/130312109-6e763f32-285e-4be5-b872-f5bcf73f8d46.png)

**Comment by alfaman09** [comment]
I get the same message as the above post any time I try to use Refresh Filter button. If I am not on /dnd then it sends the chat a random string of code.

**Comment by rayan-1616** [comment]
I have this problem too

**Comment by freddirty** [comment]
Same Comexception here too after hit update filter. It was worked before. Just started to use yesterday, today I can not update filter.
Are there any workarounds?

**Comment by freddirty** [comment]
OK, I have the root cause.

Short workaround: stop slimtrade for the time beeing.

Long explanation:
Another application using the clipboard and this app is not prepared for this. 
This row in the source:  
Clipboard.SetText(BuildChatCommand());
causing the problem.
This row must be put into a for loop which tries several times, and inside the for loop a try-catch must be used to catch the exception what we see.
This would be the correct solution in source "ReloadItemFilter.cs" (thanks to google search :)

for (int i = 0; i < 10; i++)
{
    try
    {
        Clipboard.SetText(BuildChatCommand());
        return;
    }
    catch { }
    System.Threading.Thread.Sleep(10);
}

**Comment by HiMarioLopez** [comment]
This should be fixed by #268 

Please re-open a new issue if you need anything else! Thanks for your report.
