### ISSUE TITLE
Rate Limit Exceeded! Waiting...

### ISSUE THREAD

**Issue by dtpesyna** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#276]
Tried refreshing and adding new poe session id. Logging out and logging in again. Same message.

**Comment by dtpesyna** [comment]
I rolled back to 1.2.6. the application is now fetching. everything is working

**Comment by HiMarioLopez** [comment]
Working to understand why this is happening to a few folks. What OS version are you running on? Any apps that you’re using in conjunction with ours? Specifically those that also track changes in the games’ client.txt log file.

**Comment by gwntd541** [comment]
Same issue, can recreate if you specify more than 3 index of tabs to look through.

Stash tab mode: ID 0,1,2,3 - breaks
Are you sending multiple requests for stashtab?

limit to 3 stashs, seems to fix. But must restart client.

**Comment by skvadr** [comment]
I had this problem too, seemed to be because of Exile Diary tool that I was using.

**Comment by dtpesyna** [comment]
When I first discovered the bug I was using no other POE tools. No apps were open besides chaos recipe enhancer. I was however trying to fetch more than three tabs.

**Comment by paulohvmatos** [comment]
I also have this issue.
I'm using Windows 10 21H1 and no other tools besides CRE.
I'm fetching tabs by prefix "*", 8 tabs in total.

**Comment by T012m3n7oR** [comment]
@HiMarioLopez 
I attempted to debug this, because when manually making the request GGG does reply with a 200 OK response.

Response Headers include:
x-rate-limit-account: 45:60:60,240:240:900
x-rate-limit-account-state: 1:60:0,3:240:0

This sets rate limits from [here](https://github.com/kosace/EnhancePoEApp/blob/afad67b416dd1acfad16e06d040fdcabaf584823/EnhancePoE/Model/ApiAdapter.cs#L157).
Maximum Requests are set to 10 from [here](https://github.com/kosace/EnhancePoEApp/blob/afad67b416dd1acfad16e06d040fdcabaf584823/EnhancePoE/Model/RateLimit.cs#L25).

[This](https://github.com/kosace/EnhancePoEApp/blob/afad67b416dd1acfad16e06d040fdcabaf584823/EnhancePoE/Model/ApiAdapter.cs#L123) should be checking rate limit exceeded by checking if 1 >= 10 - 4.  This is false and therefore doesn't hit the rate timeout.

[This](https://github.com/kosace/EnhancePoEApp/blob/afad67b416dd1acfad16e06d040fdcabaf584823/EnhancePoE/Model/ApiAdapter.cs#L195) is the other rate limiter that I can see.
1 >= 10 - Tabs - 4
1 >= 6 - Tabs
According to this I would expect having greater than 4 tabs to error out, which is exactly what @gwntd541 has discovered.

**Comment by MyLego** [comment]
I have had the same issue. Changed to 3 tabs and it went away for a little while but returned even with 3 tabs.

**Comment by paulohvmatos** [comment]
> I rolled back to 1.2.6. the application is now fetching. everything is working

Thx for sharing. I tried this and it solved the issue for me.
