### ISSUE TITLE
bugs in --> Chaos Recipe Enhancer 1.1.2

### ISSUE THREAD

**Issue by nshaltern** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#28]
![Screenshot (14)](https://user-images.githubusercontent.com/46297012/103354533-1ad61480-4aac-11eb-9d19-582312338d4e.png)
hiho i test it atm. first. thx for the counter in the overlay its really nice to have :)
here the bugs i see atm:

1. Complete sets dont count in the overlay. (stay on 0 the whole time)
2. atm i see only armours get hide when i have 12/12... atm boots and gloves show me 12+ on the counter and not hide. (Full Set Treshold is 12)
3. Rings and one handed weapons dont get count as a single one (1 Ring in Stash = overlay show 0 // 2 rings in stash = overlay show 1)
4. Notification Sound is activated but dont work by fetching
5. i have 3 complete sets in my stash but the "Set counter" show 0 .... the item amounts counter shows it ok. 
6. when i go to my stash and click on "Stash" to get show a set i dont see any because the sets dont get count in the set counter.

**Comment by kosace** [comment]
Hello,

1. make sure you activate Fill Greedy. You dont have enough low ilvl items probably.
2. did you refresh your lootfilter ingame?
3. that is intended. It shows you the amount of sets you can make with your amount of items
4. it only plays when you have to refresh your lootfilter, not everytime it fetches. Or did I misunderstood?
5. same as 1. Activate Fill Greedy. Otherwise it will only stick 1 low ilvl item in each set.
6. Only full sets are shown. Thats why its empty.

**Comment by nshaltern** [comment]
okokok :) so that was my own bugs :) now it works great!!!! it was my setup (disable Fill Greedy) Ty for the fast helping hand. Now waiting for the comming leaguestart :) ty and gl

**Comment by kosace** [comment]
There will be some updates and bug fixes until league start.  1 common crash will be fixed in next update. Probably today or tomorrow.
