### ISSUE TITLE
doesnt highlight items on they own

### ISSUE THREAD

**Issue by XenosTec** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#290]
i need to reload item filter, after i did the chaos recipe that it highlight the items again
and sometimes i need to reload it, so it doesnt highlight the items anymore

using local lootfilter

**Comment by HiMarioLopez** [comment]
Having a bit of a hard time deciphering your issue. Can you explain in more detail, please? Maybe some reproduction steps? Thanks!

**Comment by XenosTec** [comment]
sry for my bad englisch, i created a video where you can see what i mean and maybe even a solution to it

https://youtu.be/5ICMSbRGy3k

and ps: the hitbox for the overlay needs to be bigger, i need sometimes to lick many times over and over that it goes to the next item

**Comment by HiMarioLopez** [comment]
If I'm understanding the video correctly, you're asking us to put in an auto-reload filter after updates were made to the state of your stash.

Just saw the video, unfortunately we can't do an auto-filter reload as we're pretty conservative with what we want to automate and what we won't automate due to not risking the accounts of our users for the app.

If that didn't answer your question please comment and we'll re-open this...
