### ISSUE TITLE
Stashtab Highlight issues

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#3]
1. does the stashtab highlight avoid highlighting items that are lootfiltered by other rules such as 4-links?
2. control click to transfer an item sometimes doesn't clear and advance the current highlight.
3. it would be better to just highlight all matching items (for one set) and clear the highlight as each item is transferred.

**Comment by kosace** [comment]
hey

1. yes thats true, because the rules will be added on top of the lootfilter. thats why you can add recognition phrases in your lootfilter to decide where the rules should be placed (you have to redownload the app, cause i (hopefully) fixed a bug in parsing)
2. im working on that. the problem is that you click on the border of the buttons in there. i am working on a better solution.
3. i will think about giving the option to do it that way. originally the idea was to get 2 full sets in your inventory to sell faster. thats why order was important. but its probably a good idea to have the option.,

Thanks for reports

**Comment by kosace** [comment]
Okay I misunderstood your 1. issue.

No the stashtab overlay considers all items which fit the profile: ilvl60-74, unid and rare. The problem is, how would you find out, which items to not conisder? I would have to parse and interpret the whole itemfilter. I mean technically I could probably implement it, but it would be a lot of work. Not my first priority

**Comment by kosace** [comment]
to 2. I included the button border sizes into the calculation. It should be a bit more precise now.
