### ISSUE TITLE
Error when using the app

### ISSUE THREAD

**Issue by Strikenn** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#304]
Hi
I get this error whenever I enable loot filter manipulation.
I click reload filter and then fetch and the error appears.

![error](https://user-images.githubusercontent.com/26554385/153633153-86187fb8-abdb-4c33-ad03-57369933aa9f.png)

**Comment by HiMarioLopez** [comment]
Try re-running the app in Admin mode. Let me know if that fixes it

**Comment by Strikenn** [comment]
I get the same error if running in Admin mode.
Also tried downloading a standard loot filter from FilterBlade and the same thing happens.

**Comment by killt704** [comment]
i have been getting the same error since yesterday, i have tried reinstalling, i cant even get the overlay up anymore to change the settings or anything.  i even went as far as to try to clean out old registry files after uninstalling and deleteing the config files.   After reinstalling it, still that same error..
![chaos error](https://user-images.githubusercontent.com/81832984/153654997-c7511f1f-402a-4d40-bc2d-2de59b5e6f3f.png)

**Comment by HiMarioLopez** [comment]
Hey thanks! These errors are different. Gonna take a look at both of them

**Comment by Strikenn** [comment]
I am no longer having this issue.

**Comment by devilmanza2099** [comment]
Hi, I have problem like this also
![272585963_482391403283267_515812605755264820_n](https://user-images.githubusercontent.com/99561991/153728727-199a7da1-beda-4fd7-993a-3de5300b2f2f.png)

Please help me

**Comment by HiMarioLopez** [comment]
> Hi, I have problem like this also ![272585963_482391403283267_515812605755264820_n](https://user-images.githubusercontent.com/99561991/153728727-199a7da1-beda-4fd7-993a-3de5300b2f2f.png)
> 
> Please help me

Have you tried launching the app in admin mode?

**Comment by HiMarioLopez** [comment]
My main recommendations for any access issues:

1) Try running in admin mode
2) Add our app to your anti-virus exceptions if able
