### ISSUE TITLE
[Bug] Can't scan stash without specifying filter (even with Loot Filter Manipulation is toggled off)

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#338]
# v1.5.0

I'd like to only use the scan feature, and not use the filter manipulation feature.
I can't scan my stash without specifying a filter to use

![image](https://user-images.githubusercontent.com/15201298/168106798-42bb1b46-11a4-45de-8c42-986bab6fe419.png)

**Comment by HiMarioLopez** [comment]
Good catch. That is definitely a bug. I'll be sure to fix that in tonight's patch.

**Comment by HiMarioLopez** [comment]
Indeed looks fixed in 1.5.4

![image](https://user-images.githubusercontent.com/23390842/168872701-fadd445c-c902-4575-8202-2587a79d391b.png)
![image](https://user-images.githubusercontent.com/23390842/168872706-ab0571fa-5af4-445f-8b7d-ff48008c36b1.png)
![image](https://user-images.githubusercontent.com/23390842/168872713-ff37fc2e-8d24-4f72-b4a4-68906df63c22.png)

Please open a new issue if you run into any more problems. Thanks!
