### ISSUE TITLE
[Bug] 1.5.0 bug report

### ISSUE THREAD

**Issue by dovry** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#339]
## Non-admin mode
- [x] filter.filter is not manipulated (unless in admin)
  - #338
- [x] pastes clipboard 50% of the time when reloading filter from UI
  - #334 
![image](https://user-images.githubusercontent.com/15201298/168262459-a5ee4365-e7bf-43b4-94ae-5d5311291c13.png)

## general issues, not sure if 1.5.0 is to blame
- [x] freezes ALL input for 2-10 seconds if I reload my filter more than 1/sec via the overlay, then acts on all inputs once the computer responds again
- [x] closing stash overlay from taskbar crashes application

**Comment by HiMarioLopez** [comment]
> ## general issues, not sure if 1.5.0 is to blame
> * [x]  freezes ALL input for 2-10 seconds if I reload my filter more than 1/sec via the overlay, then acts on all inputs once the computer responds again

My general advice for this bit is... do not reload your filter more than 1 time a second haha. There's a chain of inputs that happens when you click that button, and you will basically be trying to do a gazzillion input operations a second which is bound to cause issues.

> * [x]  closing stash overlay from taskbar crashes application

This has been fixed in the latest versions

Closing this issue up as we're actively tracking the clipboard issue in #379 

The filter issue you referenced in your first point has been fixed, but the wording on your task is different. If you wish to open a new issue with more detail that would be great, thanks!
