### ISSUE TITLE
Filter not updating unless active is selected

### ISSUE THREAD

**Issue by jibby1445** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#356]
Hi,

Having some issues once I entered yellow / red maps.

The filter is no longer updating unless i switch all of the items to "active" 

That's the work around for now. If they are not active they do not show up on the filter even if I am not at my count of 10.

**Comment by Netaxo** [comment]
Having the same issue. It wont show "filler" items in my lootfilter when im in yellow / red maps.

also: it wont register my finished sets. my count ist set to 6 and thats my overlay atm

https://i.imgur.com/WsyAOUl.png

it say 0 sets while im at 10 or so.

**Comment by lukezamboni** [comment]
I got the same problem. Sets is counting correctly, but items are not being highlighted in high tier maps. perhaps something to do with the regal or exalt recipes, which arent enabled on my client.

**Comment by HiMarioLopez** [comment]
This has been fixed in the latest release, 1.5.4

We were unintentionally hiding higher item level items to complete your sets, and only showing 60 - 74 items (which isn't required if you already have one).

Please open new issue if the issue persists, and include as much detail as possible. Thanks!
