### ISSUE TITLE
Clicking Reload Filter button sometimes puts Hex code for item color into chat

### ISSUE THREAD

**Issue by herofromhyrule** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#364]
I'm having an issue where sometimes when I push the reload filter button to manually force a reload the Hex code that I am using for item colors in the app gets thrown into chat instead and nothing happens to the filter. I have to click the reload button again to get the filter to properly reload.

I'm using version 1.5.2.0 running on Windows 10 21H2

**Comment by HiMarioLopez** [comment]
Seems to be an issue with the hook we have for keyboard events. It's pasting whatever is currently in your clipboard to the in-game chat. Will be looking into this

**Comment by InsanityPrelude** [comment]
In relation to this, I'm looking at ReloadItemFilter.cs and I'm pretty sure it's an error that occurs on subsequent presses of the Reload Filter button.  It usually seems to work just fine for me at least once, but after I've been playing for a while it seems like something goes weird.  

1. Save the Old Clipboard
2. Build a Reload Command "/filter name_of_filter"
**3. Retry Loop for .NET Implementation of Clipboard**
4. Select the PoE Window
5. Press Enter
6. Press Control+V
7. Press Enter
8. Restore the Previous Clipboard

The problem seems to originate at number 3, somewhere around Line 81 of ReloadItemFilter.cs.  Given how crazy that code seems to be for what it does, I imagine this must be a well known finicky bit of code.

I recommend going to the Stack Overflow page linked in the comments there and checking the much lower solution posted by user "Mar" in 2015 for creating a static class for managing the clipboard a bit more efficiently, assuming this wasn't seen and discarded previously for not working in this use case.

**Comment by HiMarioLopez** [comment]
This is really great inside. I have been testing this bit the last few minutes and it's being finicky for me, as well. It's not always reloading my filter properly. I'll take a look at the comment right now

**Comment by HiMarioLopez** [comment]
Tested the solution locally and it works like a charm. Also much faster (maybe placebo from doing this so many times haha)

https://github.com/kosace/EnhancePoEApp/commit/de326983dee2d0488bfc40bc796648560b5095c0

Will be out with the next patch. Thanks for your contribution
