### ISSUE TITLE
Suggestion: Overlay / Loot filter options

### ISSUE THREAD

**Issue by Slackalot** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#40]
Options for size of loot filter icons and the overlay size would be useful

**Comment by HiMarioLopez** [comment]
Since the time of this issue being opened, we've added a few different size options for the overlay - standard, minimal, and only buttons.

For modifying the loot filter styles you can navigate to the installation directory, and there you'll find 'NormalItemStyles.txt' and 'InfluencedItemStyle.txt' which you can edit in your text editor of choice; we use those templates when modifying your filters.

Here's the location of that directory: C:\Program Files (x86)\ChaosRecipeEnhancer\Styles

Let me know if you need further clarification on these things.
