### ISSUE TITLE
[Bug] [Filter Manipulation] Loading incorrect loot filter on when pressing the "Reload Filter" button

### ISSUE THREAD

**Issue by userQanar** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#407]
# Expected Behavior

So i want to choose the path to my " strict heist filter"
and be able for it to load/reload and manipulate the filter i chose 

# Current Behavior

so it manipulates the right filter ...but the big catch is it is reloading the wrong filter constantly 

-> so i click Reload Filter -> strict heist filter gets updated -> opens ingame settings -> loads the filter named semi strict heist test

-> i cant see any items highlighted and need like 3 hours to figure its constantly loading the wrong filter that i did not choose

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1          ..... probably have 2 filters with close to same name semi strict and strict 
2. step 2           whatever click reload and see the wrong filter load ? 
3. you get it...

## Context

  -> i dont think this context thingy matters on my problem 
* Operating System:
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

------> i have realy no clue how it reloads a wrong filter inside poe itself ... maybe you are passing some kind of strings ingame to the reload menu ? cant realy follow that ..... and yes i will probably just differenciate the filters by a mile in its name to fix this forever but i guess other people will die by the problem too if they just dont get it that its loading a 1x less strict filter and not the filter you choose in app menu directory 

## Failure Logs

no failure logs im just mad

**Comment by Cllyde** [comment]
To reload the filter it does send a value to the chatbox in-game: "/itemfilter " + filterName
So after reloading with the app, press Enter in-game then press the up arrow key to see exactly what item filter name was reloaded. That should match the name of the filter you set in the 'Loot Filter Location' field.

If it doesn't match, I'd say it was a bug, but if it does match, and the wrong filter was loaded, it may just be a filter name issue like you said, and you'd have to have sufficiently different filter names to avoid the issue.

**Comment by HiMarioLopez** [comment]
@userQanar This has indeed been reported before by some users. Sometimes filters with the same (or rather, very similar) name have issues with the reload filter command.

I haven't had a chance to quite look into this yet

**Comment by HiMarioLopez** [comment]
Another thing that was mentioned to me is to make sure the loot filter file name is not in all caps. Will continue to investigate this, though.

**Comment by InsanityPrelude** [comment]
I might have figured out a potential cause related to this.  A capital letter D will get hijacked by Awakened PoE Trade, because typing Shift+D will trigger one of its functions.  However it's intercepting keypresses looking for Shift+D, it yoinks it out of the loot filter reload command.  "CDR Early Chaos Filter" becomes "C Early Chaos Filter" because it takes control away for a split second.

**Comment by HiMarioLopez** [comment]
So what I've realized related to this issue is lots of folks have an offline filter with the same name as a filter they have on their online PoE account. For instance: `NeverSink-Strict` or something. And when we reload the filter via the command line it prioritizes the online version. I'll work to add a warning that lets players know they didn't load the right filter, and they should change the name of their filter file so that it doesn't match the online filter and cause those inaccuracies. 

May not be 100% the issue you're seeing but it is definitely related to issues folks have been having when hitting the reload filter button.

**Comment by ZerkerEOD** [comment]
When I do this, I have it load my online filter instead of my offline filter. Is there any way to prevent that without removing my online filters completely?

**Comment by HiMarioLopez** [comment]
Is renaming your offline filter to something distinct an option? I'd recommend that @ZerkerEOD
