### ISSUE TITLE
[Bug] [Overlays] Stash Tab Headers overflow to multiple rows if too many are selected

### ISSUE THREAD

**Issue by RobertoJKN** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#454]
**Is your feature request related to a problem? Please describe.**
I want to use multiple tabs, some of them are inside folders, but the overlay doesn't include folder options and in the overlay there are 2 tab rows (the game only has 1 row which you cycle through), which makes it hard to use. Also, when using both Quad and Normal sized tabs, the overlay doesn't scale properly, I have to edit it everytime I swap tabs.

**Describe the solution you'd like**
A way to "simulate" the stash tab, using an arrow to cycle through all tabs (just like in game) instead of multiple rows.

**Describe alternatives you've considered**
Maybe in the app config, we could add each individual tab index (or preffix/suffix) alongside what stash type they are (so the scaling
matches properly).
**Additional context**
![image](https://user-images.githubusercontent.com/32022277/212186132-a2c11309-1b1b-4ddb-a3d6-6486d5a550bc.png)
![image](https://user-images.githubusercontent.com/32022277/212186860-b620b50f-8a29-4f17-957a-b02ff060d69a.png)

**Comment by HiMarioLopez** [comment]
in practice i would never recommend users to select more than a few tabs due to how it will end up loooking

but one thing i've learned is that i can build out new features to support how y'all use it! so here's a new setting:

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/b63d88bb-4682-4e45-96e9-12f45a0c6c77)

"Horizontal Gap to Stash Grid" will allow users to add a "gap" between the grid and their tabs so they can better interact with them without too much clutter

it's still clunky IMO from a UX perspective but i realize some poeple want to do it this way and that's ok

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/b3c1c96e-ef3c-4aab-a620-9f72f6f042fa)
