### ISSUE TITLE
[Bug] [Overlays] "This Visual is not connected to a Presentation" InvalidOperationException on Vendoring Set

### ISSUE THREAD

**Issue by ne0ark** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#509]
# Expected Behavior

No Error

# Current Behavior

Crashes after selling items.

## Steps to Reproduce

No Clue

The file path shown in the error log is incorrect. D drive is a USB Drive.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Chaos Recipe Enhancer Version:
* Operating System: Win 11
* Chaos Recipe Enhancer Settings (XML file or screenshot will suffice):

## Failure Logs

Please include any relevant log snippets or files here.

## Additional Attachments (e.g. Screenshots, Videos)

<img width="305" alt="image" src="https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/660607/05b54742-d10d-4e03-b0a7-ea4cd400aa2f">

**Comment by HiMarioLopez** [comment]
Another report of the same issue: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/issues/502

![image](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/assets/23390842/a19aa6dd-8207-4dc7-a9e1-3b2177e45808)

**Comment by HiMarioLopez** [comment]
I have made the following change that hopefully resolves this issue: https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/commit/dd06391a1aedc7ec431433952b60137e48f74fc3#diff-6ae11fafaf5ba130fd29f21ffeb3b97d75d68232f1ed18edab4fd2b8b6de3499

I hope, only because I was never able to reliably reproduce the issue in the first place. I can say, though, that I didn't get the issue again during testing after this change was made. Please open a new issue if you get this error message again, thanks.
