### ISSUE TITLE
Fetch Start/Stop button is difficult to use

### ISSUE THREAD

**Issue by bjbeare** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#54]
With the need to avoid getting temp-banned from the server... the fetch stop/start button is difficult/annoying. I suggest that it be replaced with a 'fetch' (now) button. There really is little point in doing fetches while not actually "at" your stash. Fetches should performed at the following times:

- when fetch clicked
- when the overlay is made visible
- when the grid is made visible

Also...
- During the fetch operation, the button should change color to indicate that the operation is in progress.
- the button should change to a 3rd color after a fetch to indicate that it is in a lock-out interval (say... 10 seconds?) and go green again when the lockout is cleared.

Green: push it to initiate a fetch
yellow: fetching now
grey: can't fetch for a few more seconds.

**Comment by kosace** [comment]
i will change how that works anyways. right now it just fetches periodically. fetch now button could actually be non intuitive also since poe servers have stale data very often. and you would expect fresh data on clicking the button right. 

i will probably do a fetch now button in the future and combine that with automatic fetches when entering new zones but that takes some time.

you cant get temp banned anymore btw. the tool catches that.
