### ISSUE TITLE
[Bug] [Unsorted] *League dropdown empty*

### ISSUE THREAD

**Issue by ChaosDMG** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#598]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest release (not a beta / pre-release)
- [x] I checked the FAQ and found no common resolution for my issue
- [x] I checked to make sure that this issue has not already been filed (by doing a quick search in the ![issue tracker](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/issues))

# Expected Behavior

![image](https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/assets/10861785/663b19c5-1691-4b80-99af-1ebf280562ed)

**Comment by DezZzO** [comment]
Same issue!

**Comment by TerroR75** [comment]
Same here

**Comment by bakedmotato** [comment]
Broken for me too. Tried reinstalling / logging back in, but no luck!

Edit: Seems to be working now after restarting my game! On v3.24.2000.
Edit 2: Never mind. I'm getting a rate limited error.

**Comment by dorianturle** [comment]
Same here

**Comment by Ju8z** [comment]
Same for me. Tried to download https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.24.2000 but BitDefender identifies it as a virus.

**Comment by son0013** [comment]
same

**Comment by Erodraeda** [comment]
same here

**Comment by HiMarioLopez** [comment]
3.24 launch did not go as intended. I’ve since removed those releases and their associated installers, and rolled back all associated backend components.

I will be review what went wrong - for the meanwhile 3.23.1005 is the latest stable release.

You can find the latest installers here: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases
