### ISSUE TITLE
[Bug] [Unsorted] "Rate Limit Exceeded" error immediately upon logging in, and then logs me out and crashes.

### ISSUE THREAD

**Issue by hb-wright** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#599]
Every time I launch the program, I am signed out of my PoE account. I click the "log in" button and successfully log in through PoE's Oauth signin page. Chaos Recipe Enchancer shows me as logged in, but immediately throws a "rate limit exceeded" error saying I need to try again in 4m57s (or so - 5 min minus a few seconds each time). When I x-out of the error, the "account" tab returns to a "Not Logged In" state and then the program promptly crashes. This happens every time I open the program.

I am using the latest version released a few hours ago, 3.24.2000. Running Windows 10 Pro

**Comment by HiMarioLopez** [comment]
3.24 launch did not go as intended. I’ve since removed those releases and their associated installers, and rolled back all associated backend components.

I will be review what went wrong - for the meanwhile 3.23.1005 is the latest stable release.

You can find the latest installers here: https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases
