### ISSUE TITLE
Tool not recognizing upper limit for belts?

### ISSUE THREAD

**Issue by snwkill** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#73]
As you can see i have it set up for 10 sets, for some reason it is going over on belts
![image](https://user-images.githubusercontent.com/31193671/104821379-66f1ba80-5809-11eb-9686-dd3b4493b429.png)

**Comment by Omniwrath** [comment]
That's because it is counting belts as jewelry alongside rings and amulets. With rings and amulets, you would NEVER want to skip those, because those will inevitably be your bottleneck. While belts can sometimes be the bottleneck when you first start doing the chaos recipe, this is a temporary problem at most, and really only comes up if you're only keeping 1 set on hand at a time.

The default behavior for belts definitely needs changing. I'd like to see it obey the set threshold, but I'd be satisfied with belts having 2x of the set threshold, just to be safe.

**Comment by jmsMaupin1** [comment]
as you can see Im having similar issues, but with everything except chests? (not sure about jewelry just yet.)

![image](https://user-images.githubusercontent.com/14814506/104859768-882fd500-58f5-11eb-897e-3604092a6025.png)

**Comment by kosace** [comment]
Update to 1.1.5 to Set which items are always on. 

@jmsMaupin1 activate fill greedy
